ErrorPirate/DWBH

- .idea/misc.xml
- .idea/modules.xml
- backend/.gitignore
- backend/build.gradle
- backend/src/main/java/com/dwbh/backend/BackendApplication.java
- backend/src/main/java/com/dwbh/backend/config/BeanConfig.java
- backend/src/main/java/com/dwbh/backend/config/SwaggerConfig.java
- backend/src/main/java/com/dwbh/backend/config/WebConfig.java
- backend/src/main/java/com/dwbh/backend/controller/MainController.java
- backend/src/main/resources/application.properties
- backend/src/main/resources/application.yml
- backend/src/main/resources/log4jdbc.log4j2.properties
- backend/src/main/resources/logback-spring.xml
- backend/src/main/resources/schema.sql
- docker-compose.yml
기본 개발 세팅 
- **해결할 이슈**: Closes #4
- **핵심 변경 내용**: 스프링 부트 자바 개발 세팅
- **주요 변경 파일 및 모듈**: 
application.yml
build.gradle
log4j 설정
- [✅] 코드가 컴파일/빌드 됨
- **테스트 추가 여부**:  없음
- **테스트 환경**:  로컬 PC (예: 브라우저, Node 버전, 운영체제)
> feat: 기본 개발 세팅

- backend/src/main/java/com/dwbh/backend/common/aggregate/YnType.java
- backend/src/main/java/com/dwbh/backend/common/util/DateTimeUtil.java
- backend/src/main/java/com/dwbh/backend/exception/CustomException.java
- backend/src/main/java/com/dwbh/backend/exception/ErrorCodeType.java
공통 코드 일부 추가
- **해결할 이슈**: Closes #11 
- **핵심 변경 내용**: 새로운 코드 추가
- **주요 변경 파일 및 모듈**: common 파일
> feat: 공통 코드 일부 추가

- backend/src/main/resources/schema.sql
- **해결할 이슈**: Closes #17 
- 완성된 모델링의 DDL 파일 수정해서 올림
> refactor: 스키마 리펙토링

- backend/src/main/java/com/dwbh/backend/entity/Chat.java
> feat: Chat entity 추가

- backend/src/main/resources/dummy_data.sql
add dummy_data.sql
- **핵심 변경 내용**: 데이터 추가
- **주요 변경 파일 및 모듈**: dummy_data.sql
- **구현 내용**: add dummy_data.sql
> feat: add dummy_data.sql

- backend/src/main/resources/schema.sql
ddl 수정(schema.sql)
Closes #17  [refactor] 스키마 DDL 리펙토링
- schema.sql 수정(DDL에 fk 추가)
> refactor: schema.sql 리펙토링

- backend/src/main/java/com/dwbh/backend/controller/evaluation/EvaluationController.java
- backend/src/main/java/com/dwbh/backend/dto/evaluation/EvaluationDTO.java
- backend/src/main/java/com/dwbh/backend/dto/evaluation/EvaluationRequest.java
- backend/src/main/java/com/dwbh/backend/entity/Evaluation.java
- backend/src/main/java/com/dwbh/backend/entity/evaluation/Evaluation.java
- backend/src/main/java/com/dwbh/backend/exception/GlobalExceptionHandler.java
- backend/src/main/java/com/dwbh/backend/repository/evaluation/EvaluationCustomRepository.java
- backend/src/main/java/com/dwbh/backend/repository/evaluation/EvaluationRepository.java
- backend/src/main/java/com/dwbh/backend/repository/evaluation/EvaluationRepositoryImpl.java
- backend/src/main/java/com/dwbh/backend/service/evaluation/EvaluationService.java
평가 crud 기능 구현
- **해결할 이슈**: Closes #25 
- 평가 컨트롤러, 서비스, 레포지토리 코드 추가
- 평가 request 추가
- 평가 DTO 수정
- 글로벌예외 처리 적용을 위한 GlobalExceptionHandler 클래스 파일 추가
- 조회를 제외한 나머지 평가 crud 기능 구현
- 글로벌 예외 처리 적용을 위한 클래스 파일을 추가했기 때문에 예외 처리시 사용하시면 됩니다.
- postman 에서 테스트 확인( 작성, 수정, 삭제 )
Auditing 설정과 chatRepository  사용이 필요한데 만들고 계신거 같아서 올리지 않습니다. 
따라서 파일 위치에 따른 에러가 발생할 수 있습니다.
> feat: 평가 crud 기능 구현

- backend/src/main/resources/dummy_data.sql
- backend/src/main/resources/schema.sql
연관관계에 맞는 DROP TABLE 구문 순서 수정, dummy_data 입력
- **해결할 이슈**: Closes #36
- **핵심 변경 내용**: DROP TABLE 순서 수정, dummy_data 입력 순서 수정
- **주요 변경 파일 및 모듈**: dummy_data, schema.sql
- [✅ ] 코드가 컴파일/빌드 됨
- [✅ ] 테스트가 통과함 (단위 테스트 및 통합 테스트 포함)
- [ ✅] 문서가 업데이트됨 (필요시)
- **테스트 환경**: HeidiSQL 구문 실행으로 테스트 완료
> refactor: dummy_data, schema.sql 수정

- backend/src/main/java/com/dwbh/backend/controller/chat/ChatController.java
- backend/src/main/java/com/dwbh/backend/controller/notification/NotificationController.java
- backend/src/main/java/com/dwbh/backend/dto/chat/ChatDTO.java
- backend/src/main/java/com/dwbh/backend/mapper/ChatMapper.java
- backend/src/main/java/com/dwbh/backend/service/chat/ChatService.java
- backend/src/main/java/com/dwbh/backend/service/notification/NotificationService.java
chatDto.java - inner class 이름 변경
- **핵심 변경 내용**: 이름 변경
- **주요 변경 파일 및 모듈**: chatDto.java
- **구현 내용**: chatDto.java - inner class 이름 변경
- **코드 영향 범위**: chatDto 사용하는 코드 확인 필요
> refactor: chatDto.java - inner class 이름 변경

- backend/src/main/resources/schema.sql
counsel_offer 테이블 ddl 변경
file 테이블 ddl 변경
댓글 테이블 비밀댓글여부 기본값 제거
파일 테이블 file_type 길이 변경
댓글 테이블 비밀댓글여부 기본값 제거
파일 테이블 file_type 길이 변경
> refactoring: 댓글 테이블, 파일 테이블 변경

- backend/src/main/java/com/dwbh/backend/dto/chat/ChatDTO.java
- backend/src/main/java/com/dwbh/backend/service/evaluation/EvaluationService.java
- backend/src/test/java/com/dwbh/backend/service/chat/ChatServiceTest.java
- backend/src/test/java/com/dwbh/backend/service/evaluation/EvaluationServiceTest.java
- backend/src/test/java/com/dwbh/backend/service/notification/NotificationServiceTest.java
채팅방, 알림 엔드포인트 및 서비스 테스트
- **해결할 이슈**: Closes #44
- **핵심 변경 내용**: 테스트 진행
- **구현 내용**: junit으로 진행한 ServiceTest 작성
- **코드 영향 범위**: ChatDTO에 create 요청 내부 클래스에 생성자 입력 어노테이션 추가
- **테스트 환경**: junit, postman
시큐리티 적용 후에 다시 테스트를 진행할 필요 있음
> test: 채팅방 및 알림 테스트

- backend/src/main/java/com/dwbh/backend/common/util/AuthUtil.java
- backend/src/main/java/com/dwbh/backend/controller/UserController.java
- backend/src/main/java/com/dwbh/backend/dto/UserDetailResponse.java
- backend/src/main/java/com/dwbh/backend/dto/user/UserModifyResponse.java
- backend/src/main/java/com/dwbh/backend/entity/User.java
- backend/src/main/java/com/dwbh/backend/entity/UserProfileFile.java
- backend/src/main/java/com/dwbh/backend/mapper/ChatMapper.java
- backend/src/main/java/com/dwbh/backend/mapper/NotificationMapper.java
- backend/src/main/java/com/dwbh/backend/repository/user/CustomUserRepository.java
- backend/src/main/java/com/dwbh/backend/repository/user/UserRepository.java
- backend/src/main/java/com/dwbh/backend/service/UserService.java
- backend/src/main/java/com/dwbh/backend/service/counselor_hire/CounselorService.java
회원 조회 추가
- **해결할 이슈**: Closes #46
- **핵심 변경 내용**: 회원 상세 조회 추가, 회원 정보 수정 조회 추가
> feat: 회원 조회 추가

- backend/src/main/java/com/dwbh/backend/common/util/FileUploadUtils.java
- backend/src/main/java/com/dwbh/backend/controller/offer/OfferController.java
- backend/src/main/java/com/dwbh/backend/repository/offer/OfferInfaRepositoy.java
- backend/src/main/java/com/dwbh/backend/repository/offer/OfferRepository.java
- backend/src/main/java/com/dwbh/backend/service/offer/OfferService.java
댓글 삭제 기능 구현
- **해결할 이슈**: Closes #69 
- **핵심 변경 내용**: 댓글 삭제기능 구현 및 첨부 파일 삭제 / 댓글 작성, 수정에 유저 권한 검증 로직 추가
- **주요 변경 파일 및 모듈**: 
- OfferController.java - 댓글 삭제 API 추가 
- OfferService.java - 댓글 삭제 로직 구현 및 파일 삭제 , 댓글 작성, 수정에 유저 권한 검증 로직 추가
- OfferRepository.java - 댓글 삭제 추가
- FileUploadUtil.java - 파일이 이미지인지 확인하는 메소드 변경
- **구현 내용**: 댓글 삭제 시 댓글에 첨부된 파일 같이 삭제됨
> Feat/#69 댓글삭제

- backend/src/main/java/com/dwbh/backend/controller/UserController.java
- backend/src/main/java/com/dwbh/backend/dto/CreateUserRequest.java
- backend/src/main/java/com/dwbh/backend/dto/user/ModifyUserRequest.java
- backend/src/main/java/com/dwbh/backend/exception/ErrorCodeType.java
- backend/src/main/java/com/dwbh/backend/service/UserService.java
각종 중복 체크
- **해결할 이슈**: Closes #45 
- **핵심 변경 내용**: 각종 중복 체크
- **구현 내용**: 
이메일 중복 체크
닉네임 중복 체크
패스워드 검증
> refactor: 각종 중복 체크

- backend/src/main/java/com/dwbh/backend/controller/UserController.java
- backend/src/main/java/com/dwbh/backend/entity/User.java
- backend/src/main/java/com/dwbh/backend/service/UserService.java
회원 탈퇴 기능 추가
- **해결할 이슈**: Closes #49
- **핵심 변경 내용**: 회원 탈퇴 기능 추가, 로그인 시 탈퇴 유저 로그인 불가
> feat: 회원 탈퇴 기능 추가

- backend/src/main/java/com/dwbh/backend/repository/counsel_offer/CounselOfferRepository.java
- backend/src/main/java/com/dwbh/backend/service/counsel_offer/OfferService.java
- **해결할 이슈**: Closes #63
- **핵심 변경 내용**: CounselOfferRepository, OfferRepository 추가
- [✅ ] 코드가 컴파일/빌드 됨
- [✅ ] 테스트가 통과함 (단위 테스트 및 통합 테스트 포함)
> refactor: repository 추가

- backend/src/main/java/com/dwbh/backend/dto/CreateUserRequest.java
- backend/src/main/java/com/dwbh/backend/dto/user/ModifyUserRequest.java
- backend/src/main/resources/dummy_data.sql
- backend/src/test/java/com/dwbh/backend/service/UserServiceTest.java
유저 서비스 테스트 코드 작성
- **해결할 이슈**: Closes #83 
- **핵심 변경 내용**: 유저 서비스 테스트 코드 작성
- **구현 내용**: 유저 서비스 테스트 코드 작성
- **코드 영향 범위**: 테스트를 위해 일부 request에 생성자 추가
- **테스트 추가 여부**: 유저 서비스 테스트 코드 작성
> test: 유저 서비스 테스트 코드 작성

- backend/src/main/java/com/dwbh/backend/controller/counselor_hire/CounselorController.java
- **해결할 이슈**: Closes #87
- **핵심 변경 내용**: 엔드포인트 수정
- **주요 변경 파일 및 모듈**: CounselorController
> refactor: 엔드포인트 수정

- backend/src/main/java/com/dwbh/backend/entity/CounselorAge.java
- backend/src/main/java/com/dwbh/backend/entity/CounselorHireAge.java
- backend/src/main/java/com/dwbh/backend/entity/CounselorHireType.java
- backend/src/main/java/com/dwbh/backend/entity/CounselorType.java
---
name: PR 템플릿
about: PR 템플릿
title: ''
labels: ''
assignees: ''
---
- **핵심 변경 내용**: (예: 새로운 기능 추가, 버그 수정, 성능 개선 등)
> feat: 엔티티 추가

- backend/src/main/java/com/dwbh/backend/config/SecurityConfig.java
- backend/src/test/java/com/dwbh/backend/component/GeminiHttpClientImplTest.java
- **핵심 변경 내용**: 게시물 조회 시큐리티 검증 제거 추가
- **주요 변경 파일 및 모듈**: SecurityConfig
- **구현 내용**: 게시물 조회 시큐리티 검증 제거 추가
- [✅ ] 코드가 컴파일/빌드 됨
- [✅ ] 테스트가 통과함 (단위 테스트 및 통합 테스트 포함)
> feat: 게시물 조회 시큐리티 검증 제거 추가

- backend/build.gradle
- backend/src/main/java/com/dwbh/backend/BackendApplication.java
- backend/src/main/java/com/dwbh/backend/common/util/JwtUtil.java
- backend/src/main/java/com/dwbh/backend/common/util/RandomStringGeneratorUtil.java
- backend/src/main/java/com/dwbh/backend/config/SwaggerConfig.java
- backend/src/main/java/com/dwbh/backend/controller/UserController.java
- backend/src/main/java/com/dwbh/backend/dto/user/SendEmailRequest.java
- backend/src/main/java/com/dwbh/backend/exception/ErrorCodeType.java
- backend/src/main/java/com/dwbh/backend/service/EmailService.java
- backend/src/main/java/com/dwbh/backend/service/UserService.java
- backend/src/main/resources/application.yml
- backend/src/test/java/com/dwbh/backend/service/UserServiceTest.java
이메일 인증 기능 추가
- **해결할 이슈**: Closes #100 
- **핵심 변경 내용**: 이메일 인증 기능 추가
- **주요 변경 파일 및 모듈**: 각종 user 계열 파일 및 설정 파일
- **구현 내용**
이메일 인증 기능 추가, 회원가입 시 이메일 인증 필요
> feat: 이메일 인증 기능 추가

- backend/Dockerfile
- frontend/Dockerfile
초기 도커 파일 작성
- **해결할 이슈**: Closes #103
- **핵심 변경 내용**: 백엔드 프론트엔드 Dockerfile 추가
> feat: 초기 도커 파일 작성

- backend/src/main/java/com/dwbh/backend/controller/UserController.java
- backend/src/main/java/com/dwbh/backend/service/EmailService.java
user 어노테이션 경로 오타 수정
잘못된 email서비스 상수 적용 수정
- **해결할 이슈**: Closes #111
> fix: user 어노테이션 경로 오타 수정 및 잘못된 email서비스 상수 적용 수정

- backend/src/main/java/com/dwbh/backend/controller/counselor_hire/CounselorController.java
- backend/src/main/java/com/dwbh/backend/dto/counselor_hire/CounselorDetailResponse.java
- backend/src/main/java/com/dwbh/backend/repository/counselor_hire/CounselorRepositoryImpl.java
- frontend/src/components/counsel/CounselList.vue
- frontend/src/css/style.css
- frontend/src/router/index.js
- frontend/src/views/counsel/CounselDetailView.vue
- frontend/src/views/counsel/CounselListView.vue
게시글 상세조회 기능 구현
- **해결할 이슈**: Closes #107
- **핵심 변경 내용**: 게시글 상세조회 기능
- **주요 변경 파일 및 모듈**: CounselDetailView.vue, CounselorRepositoryImpl
- **구현 내용**: 상세조회 구현
- ✅ 코드가 컴파일/빌드 됨
> feat: 게시글 상세조회 기능 구현

- frontend/Dockerfile
- frontend/nginx.conf
dockerfile 수정
- **핵심 변경 내용**: dockerfile 수정
- **구현 내용**: dockerfile 수정, 거기에 필요한 nginx.conf 파일 추가
> fix: dockerfile 수정

- docker-compose.yml
컨테이너 자동 재시작 설정 추가
- **해결할 이슈**: Closes #125 
- **핵심 변경 내용**: 컨테이너 자동 재시작 설정 추가
- **주요 변경 파일 및 모듈**: docker-compose.yml
- **구현 내용**: 컨테이너 자동 재시작 설정 추가
> refactor: 컨테이너 자동 재시작 설정 추가

- backend/src/main/java/com/dwbh/backend/service/chat/ChatService.java
- frontend/src/components/chat/ChattingDetail.vue
- frontend/src/components/chat/ChattingList.vue
- frontend/src/components/common/Header.vue
모달 화면 수정
- **핵심 변경 내용**:  모달 ui  수정
- **구현 내용**: 모달 ui  수정
- **코드 영향 범위**: 채팅 쪽
> feat: 모달 화면 수정

- frontend/src/components/chat/ChattingDetail.vue
- frontend/src/components/chat/ChattingList.vue
- frontend/src/components/common/Header.vue
> feat: 토큰 받아오는 값 수정

- frontend/src/components/common/Header.vue
- frontend/src/components/common/SideNotificationBar.vue
- frontend/src/components/user/RegisterForm.vue
- frontend/src/views/evaluation/EvaluationView.vue
- frontend/src/views/user/LoginView.vue
제 쪽 만든거 다시 리팩토링
로그인, 회원가입, 알림, 평가
- **해결할 이슈**: Closes #122 
- **핵심 변경 내용**: 파일 점검
- **구현 내용**: 인증 5초에 한번 되도록, 알림 유저 닉네임 받기, 평가 헤더 안보이게 하기
> refactor: 전체리팩토링

- backend/src/main/java/com/dwbh/backend/dto/chat/ChatDTO.java
- backend/src/main/java/com/dwbh/backend/repository/chat/ChatCustomRepository.java
- backend/src/main/java/com/dwbh/backend/repository/chat/ChatRepository.java
- backend/src/main/java/com/dwbh/backend/repository/chat/ChatRepositoryImpl.java
- backend/src/main/java/com/dwbh/backend/service/chat/ChatService.java
- frontend/src/components/chat/ChattingDetail.vue
- frontend/src/components/chat/ChattingList.vue
---
name: PR 템플릿
about: PR 템플릿
title: ''
labels: ''
assignees: ''
---
- **해결할 이슈**: Closes #130 
- **핵심 변경 내용**: 성능 향상
- **주요 변경 파일 및 모듈**: ChatRepository
- **구현 내용**: findAll() -> queryDSL로 쿼리 변경
- ✅ 코드가 컴파일/빌드 됨
> refactor: chatList 조회 QueryDSL로 변경

- frontend/src/components/chat/ChattingDetail.vue
- frontend/src/components/chat/ChattingList.vue
- frontend/src/components/common/Header.vue
- frontend/src/views/evaluation/EvaluationView.vue
---
name: PR 템플릿
about: PR 템플릿
title: ''
labels: ''
assignees: ''
---
- **해결할 이슈**: Closes #(이슈 번호)
- **핵심 변경 내용**: (예: 새로운 기능 추가, 버그 수정, 성능 개선 등)
> bug: authToken -> accessToken 으로 변경

- frontend/src/components/chat/ChattingDetail.vue
> Feat: 채팅 뷰 수정

- backend/src/main/resources/application.yml
쿠버네티스 대응 env 파일 optional 위치 추가
- **해결할 이슈**: Closes #137 
- **핵심 변경 내용**: env파일 경로 추가
- **주요 변경 파일 및 모듈**: application.yml
> fix: 쿠버네티스 대응 env 파일 optional 위치 추가

- backend/src/main/java/com/dwbh/backend/dto/chat/ChatMessageDTO.java
- backend/src/main/java/com/dwbh/backend/service/chat/ChatService.java
- frontend/src/components/chat/ChattingDetail.vue
> bug: 메세지 중복 발송 해결

- backend/src/main/java/com/dwbh/backend/service/chat/ChatMessageService.java
- frontend/src/components/chat/ChattingDetail.vue
- frontend/src/components/chat/ChattingList.vue
> Bug: 채팅방 버그 수정

- frontend/src/components/chat/ChattingDetail.vue
- frontend/src/views/user/LoginView.vue
bug: 닉네임 반대로 뜨는 버그 수정
bug: 닉네임 반대로 뜨는 버그 수정
브랜치 삭제하지 말아주세용
> bug: 닉네임 반대로 뜨는 버그 수정

- backend/src/test/java/com/dwbh/backend/component/GeminiHttpClientImplTest.java
> fix: 컴파일 오류를 발생시키는 테스트 코드 수정

- README.md
> docs: readme 기본 작성

- .idea/modules.xml
- .idea/vcs.xml
- backend/src/main/java/com/dwbh/backend/component/ChatMessageComponent.java
- backend/src/main/java/com/dwbh/backend/controller/chat/ChatMessageController.java
- backend/src/main/java/com/dwbh/backend/dto/chat/ChatMessageDTO.java
- backend/src/main/java/com/dwbh/backend/service/chat/ChatMessageService.java
- frontend/src/components/chat/ChattingDetail.vue
- frontend/src/components/chat/ChattingList.vue
- frontend/src/components/common/Header.vue
- frontend/src/components/counseloffer/CommentForm.vue
- frontend/src/components/counseloffer/CommentList.vue
- frontend/src/views/counsel/CounselCreateView.vue
- frontend/src/views/counsel/CounselDetailView.vue
- frontend/src/views/counsel/CounselListView.vue
- frontend/src/views/user/MypageView.vue
- frontend/src/views/user/RegisterView.vue
채팅 추천 기능 구현 수정 및 완료
- **해결할 이슈**: Closes #149 
- **핵심 변경 내용**: 채팅 추천 기능 구현 수정 및 완료
- ✅ 코드가 컴파일/빌드 됨
> 채팅 추천 기능 구현 수정 및 완료

- backend/src/main/java/com/dwbh/backend/controller/UserController.java
- backend/src/main/java/com/dwbh/backend/dto/user/ModifyUserPasswordRequest.java
- backend/src/main/java/com/dwbh/backend/entity/User.java
- backend/src/main/java/com/dwbh/backend/service/UserService.java
- frontend/src/components/common/Header.vue
- frontend/src/components/user/LoginForm.vue
- frontend/src/components/user/SearchForm.vue
- frontend/src/router/index.js
- frontend/src/views/user/LoginView.vue
- frontend/src/views/user/SearchPasswordView.vue
패스워드 찾기
- **해결할 이슈**: Closes #152 
- **핵심 변경 내용**: 패스워드 찾기를 위해 이메일이 존재하는데 체크하고, 이메일 인증 코드 발송, 코드 확인하고, 비밀번호 체크후 변경 저장
- **구현 내용**: 패스워드 찾기(변경) 구현 완료
> feat: 패스워드 찾기

- backend/src/main/java/com/dwbh/backend/repository/counsel_offer/OfferCustomRepositoryImpl.java
- backend/src/main/java/com/dwbh/backend/service/counsel_offer/OfferService.java
- frontend/src/components/counseloffer/CommentForm.vue
- frontend/src/components/counseloffer/CommentList.vue
- frontend/src/components/counseloffer/CounselCommentSection.vue
- frontend/src/views/counsel/CounselDetailView.vue
- frontend/src/views/user/MypageView.vue
댓글 생성, 조회, 수정, 삭제, 채팅방 생성 
- **해결할 이슈**: Closes #153 
- **핵심 변경 내용**: 댓글 생성, 조회, 수정, 삭제, 채팅방 생성 
> 댓글 생성, 조회, 수정, 삭제, 채팅방 생성 

- frontend/src/components/chat/ChattingDetail.vue
> bug: 닉네임 버그 수정

- backend/src/main/java/com/dwbh/backend/controller/chat/ChatMessageController.java
- backend/src/main/java/com/dwbh/backend/service/chat/ChatMessageService.java
- frontend/src/components/chat/ChattingDetail.vue
종료 후 상대방 채팅방에서도 종료 알림 보내기 기능 추가
> Feat: 종료 후 상대방 채팅방에서도 종료 알림 보내기 기능 추가

- backend/src/main/java/com/dwbh/backend/dto/counselor_hire/CreateCounselorRequest.java
- backend/src/main/java/com/dwbh/backend/entity/CounselorHire.java
- backend/src/main/java/com/dwbh/backend/entity/CounselorHireAge.java
- backend/src/main/java/com/dwbh/backend/entity/CounselorHireType.java
- backend/src/main/java/com/dwbh/backend/repository/counselor_hire/CounselorHireAgeRepository.java
- backend/src/main/java/com/dwbh/backend/repository/counselor_hire/CounselorHireTypeRepository.java
- backend/src/main/java/com/dwbh/backend/service/counselor_hire/CounselorService.java
- frontend/src/views/counsel/CounselCreateView.vue
게시글 작성 구현 (사진 미완성)
- **핵심 변경 내용**:  게시글 작성 구현 (사진 미완성)
> feat: 게시글 작성 구현 (사진 미완성)

- backend/src/main/java/com/dwbh/backend/controller/notification/NotificationController.java
- backend/src/main/java/com/dwbh/backend/dto/chat/ChatDTO.java
- frontend/src/components/notification/NotificationForm.vue
- **해결할 이슈**: Closes #(이슈 번호)
- **핵심 변경 내용**: (예: 새로운 기능 추가, 버그 수정, 성능 개선 등)
> bug: 알림 채팅방 연결 문제 해결

- backend/src/main/java/com/dwbh/backend/dto/counselor_hire/CounselorDetailResponse.java
- backend/src/main/java/com/dwbh/backend/repository/counselor_hire/CounselorRepositoryImpl.java
- frontend/src/components/counsel/CounselDetail.vue
- frontend/src/views/counsel/CounselDetailView.vue
- frontend/src/views/counsel/CounselUpdateView.vue
---
name: PR 템플릿
about: PR 템플릿
title: ''
labels: ''
assignees: ''
---
게시글 작성 구현 & 게시글 수정 구현
- **해결할 이슈**: Closes #105
- **핵심 변경 내용**: 게시글 작성 구현 & 게시글 수정 구현
- **주요 변경 파일 및 모듈**: 프론트엔드 구현 완료
> feat: 게시글 작성 구현 & 게시글 수정 구현
